### PR TITLE
plugin.yml: Fixed main class name (ChoosePlayer => Main)

### PR DESCRIPTION
**Pull request by Endermanbugzjfc**

### CODE REVIEW

**Review by SOF3 — APPROVED** [review]

**Comment by Endermanbugzjfc** [comment]
Why rebuild PHP at every job instead of making the jobs to use the build PHP job?

**Comment by SOF3** [comment]
> Why rebuild PHP at every job instead of making the jobs to use the build PHP job?

because I am lazy and would rather damage our environment by rebuilding it every time

**Comment by SOF3** [comment]
but I think I am already sharing the same `build-php` job?

**Comment by Endermanbugzjfc** [comment]
> but I think I am already sharing the same `build-php` job?

I think the error is caused by using [object Promise] in cache name.

**Comment by Endermanbugzjfc** [comment]
Stupid JS weak typing shit.

**Comment by SOF3** [comment]
I've cleared the cache. Let's retr.

**Comment by Endermanbugzjfc** [comment]
Converting to draft because staled.

**Comment by Endermanbugzjfc** [comment]
Awaiting #4.

**Review by SOF3 — APPROVED** [review]

**Pull request merged**
